### ISSUE TITLE
Can not download the pre-trained weights of ArtificiallyInspired in track1

### ISSUE THREAD

**Issue by mingqizhang** [affromero/NTIRE22_Inpainting#1]
When i run the download_models.py in track1, there was error as follow:

Traceback (most recent call last):
  File "download_models.py", line 11, in <module>
    wget.download('https://ntire-inspired.s3.us-west-2.amazonaws.com/test_submit/track1.zip', out=download_path)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/site-packages/wget.py", line 316, in download
    (tmpfile, headers) = ThrowOnErrorOpener().retrieve(url, tmpfile, callback)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/urllib/request.py", line 1822, in retrieve
    fp = self.open(url, data)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/urllib/request.py", line 1788, in open
    return getattr(self, name)(url)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/urllib/request.py", line 1998, in open_https
    return self._open_generic_http(self._https_connection, url, data)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/urllib/request.py", line 1963, in _open_generic_http
    response.status, response.reason, response.msg, data)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/urllib/request.py", line 1983, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/home/mingqi/.conda/envs/torch18/lib/python3.6/site-packages/wget.py", line 287, in http_error_default
    raise Exception("{0}: {1}".format(errcode, errmsg))
Exception: 404: Not Found

**Comment by angelacast135** [comment]
Please find the pre-trained weights in the following link: https://polybox.ethz.ch/index.php/s/lpAE4dVVNWM0lWc
Let us know if there is any issue.

**Comment by one-award** [comment]
The same error occurs in track2

**Comment by affromero** [comment]
@one-award I contacted the authors, and they provided new links, give me a second and I will update them accordingly

**Comment by affromero** [comment]
@one-award in the meantime you can access all of them here: https://drive.google.com/drive/folders/1ZNYT_rr49cDHHAsDRo9Dx2IALper0RJ9
I am copying them to a more stable place in case that link is down in the future. As they are several GBs and my current connection is not the best, it will take a while to update the links in the code. 
Please let us know if that works for you.

**Comment by one-award** [comment]
Thank you for your quick answer!

**Comment by affromero** [comment]
@one-award @mingqizhang I just updated the codes to download the pre-trained weights easily. 
Let us know if you have any issues with them, otherwise, feel free to close this issue.
